name: 💡 Feature Request
description: Suggest a new feature for the MarkItDown MCP Server
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! 💡
        
        Please provide as much detail as possible to help us understand your request.

  - type: checkboxes
    attributes:
      label: Pre-flight Checklist
      description: Please ensure you've completed these steps before submitting.
      options:
        - label: I have searched the existing issues to make sure this feature hasn't been requested already
          required: true
        - label: I have read the [Contributing Guide](../CONTRIBUTING.md)
          required: true

  - type: dropdown
    attributes:
      label: Feature Category
      description: What category does this feature fall under?
      options:
        - New file format support
        - MCP protocol enhancement
        - Performance improvement
        - Documentation
        - Developer experience
        - Claude Desktop integration
        - Other
    validations:
      required: true

  - type: textarea
    attributes:
      label: Problem Description
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented
      placeholder: I would like...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered
      placeholder: Alternatively, we could...

  - type: textarea
    attributes:
      label: Use Case
      description: How would this feature benefit MCP users? Who would use it?
      placeholder: This would help MCP users by...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Implementation Ideas
      description: Do you have any ideas on how this could be implemented? (Optional)
      placeholder: This could be implemented by...

  - type: dropdown
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Need this feature
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Contribution
      description: Are you willing to contribute to this feature?
      options:
        - label: I'm willing to submit a pull request for this feature
        - label: I can help with testing
        - label: I can help with documentation

  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request
      placeholder: Any additional information...