name: ❓ Question
description: Ask a question about using the MarkItDown MCP Server
title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question about using the MarkItDown MCP Server? 🤔
        
        Please check the documentation first, then ask your question here!

  - type: checkboxes
    attributes:
      label: Pre-flight Checklist
      description: Please ensure you've completed these steps.
      options:
        - label: I have read the [README](../../README.md)
        - label: I have searched existing issues for similar questions
        - label: I have checked the [Contributing Guide](../CONTRIBUTING.md)

  - type: dropdown
    attributes:
      label: Question Category
      description: What is your question about?
      options:
        - Installation and setup
        - Claude Desktop configuration
        - MCP protocol usage
        - File format support
        - Troubleshooting
        - Development and contributing
        - Other
    validations:
      required: true

  - type: textarea
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: Please explain your question in detail...
    validations:
      required: true

  - type: textarea
    attributes:
      label: What You've Tried
      description: What have you already tried? Include any commands, configurations, or steps you've taken.
      placeholder: I tried...

  - type: textarea
    attributes:
      label: Environment Information
      description: If relevant to your question, please provide environment details
      value: |
        - **OS**: [e.g., macOS 13.0, Windows 11, Ubuntu 20.04]
        - **Python version**: [e.g., 3.9.7]
        - **Package version**: [e.g., 1.0.0]
        - **MCP Client**: [e.g., Claude Desktop 0.4.1]

  - type: textarea
    attributes:
      label: Additional Context
      description: Any other information that might help answer your question
      placeholder: Additional details...